# Generated by Django 4.2.6 on 2023-10-31 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trade_data', '0002_alter_country_meta_country_code_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForestData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Name_Of_The_Plant', models.CharField(max_length=100)),
                ('Scientific_Name', models.CharField(max_length=100)),
                ('Local_Name', models.CharField(max_length=100)),
                ('Stock_Unit', models.CharField(choices=[('Cu_Mtr', 'Cu Mtr')], max_length=50)),
                ('Stock_Available', models.IntegerField(blank=True, default=0, null=True)),
                ('Area_Unit', models.CharField(blank=True, choices=[('Hector', 'Hector')], max_length=100, null=True)),
                ('Area_Covered', models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
    ]
