# Generated by Django 5.0 on 2024-03-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='public_unitillity',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
