# Generated by Django 4.2.6 on 2024-02-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0011_alter_tradedata_tarrif'),
        ('general_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Currency_Name', models.TextField()),
                ('Currency_Code', models.CharField(max_length=40)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
    ]
