# Generated by Django 5.0 on 2024-01-31 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0001_initial'),
        ('trade_data', '0011_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Currency_Name', models.TextField()),
                ('Currency_Code', models.CharField(max_length=40)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
    ]
