# Generated by Django 5.0 on 2024-03-22 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0002_alter_public_unitillity_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transport',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
