# Generated by Django 4.2.6 on 2024-02-06 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0011_alter_tradedata_tarrif'),
        ('general_data', '0002_currency_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Selling', models.FloatField()),
                ('Buying', models.FloatField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.currency_meta')),
            ],
        ),
    ]
