# Generated by Django 4.2.6 on 2023-11-21 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0002_alter_forestdata_stock_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestdata',
            name='Stock_Unit',
            field=models.CharField(blank=True, choices=[('Cu_Mtr', 'Cu_Mtr')], max_length=50, null=True),
        ),
    ]
