# Generated by Django 5.0 on 2024-02-02 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0003_exchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='Currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='general_data.currency_meta'),
            preserve_default=False,
        ),
    ]
