# Generated by Django 5.0 on 2024-02-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0003_publication'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budgetary_Data',
        ),
    ]
