# Generated by Django 5.0 on 2024-03-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0004_alter_land_year_alter_tourism_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='water',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
