# Generated by Django 5.0 on 2024-02-04 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0004_exchange_currency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Energy',
        ),
        migrations.DeleteModel(
            name='Energy_Meta',
        ),
    ]
