# Generated by Django 5.0 on 2024-02-04 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0005_delete_energy_delete_energy_meta'),
        ('trade_data', '0011_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Energy_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Energy_Type', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Potential_Capacity_MW', models.FloatField(default=0.0)),
                ('Current_Production_In_MW', models.FloatField(default=0.0)),
                ('Generating_Company', models.CharField(blank=True, max_length=300, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Potential_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Potential_Unit', to='trade_data.unit_meta')),
                ('Unit_Production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Unit_Production', to='trade_data.unit_meta')),
                ('Power_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.energy_meta')),
            ],
        ),
    ]
