# Generated by Django 5.0 on 2024-02-29 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0005_budgetary_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budgetary_Data',
        ),
    ]
