# Generated by Django 5.0 on 2024-03-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0005_alter_water_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
