# Generated by Django 4.2.6 on 2023-12-03 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0006_land_code_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year', models.DateField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, choices=[('Ha', 'Ha')], max_length=10, null=True)),
                ('Area', models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True)),
                ('Land_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.land_code_meta')),
            ],
        ),
    ]
