# Generated by Django 5.0 on 2024-02-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0006_energy_meta_energy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energy',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
