# Generated by Django 5.0 on 2024-03-01 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0007_budgetary_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Production_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
