# Generated by Django 5.0 on 2024-03-25 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0007_alter_populationdata_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forestdata',
            name='Year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
