# Generated by Django 4.2.6 on 2023-12-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0003_alter_tradedata_tarrif'),
        ('general_data', '0008_transport_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, choices=[('Metric Ton', 'Metric Ton')], max_length=10, null=True)),
                ('Quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Transport_Classification_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.transport_meta')),
            ],
        ),
    ]
