# Generated by Django 5.0 on 2024-03-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0002_activity_meta_activitydata'),
        ('general_data', '0009_production'),
    ]

    operations = [
    ]
