# Generated by Django 4.2.6 on 2024-03-13 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0002_activity_meta_activitydata'),
        ('general_data', '0009_production'),
    ]

    operations = [
    ]
