# Generated by Django 4.2.6 on 2023-12-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0003_alter_tradedata_tarrif'),
        ('general_data', '0010_tourism_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourism',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Number', models.IntegerField(blank=True, default=0, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Tourism_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.tourism_meta')),
            ],
        ),
    ]
