# Generated by Django 4.2.6 on 2023-12-03 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0003_alter_tradedata_tarrif'),
        ('general_data', '0011_tourism'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Name_Of_The_Hotel', models.CharField(blank=True, null=True)),
                ('Capacity_Room', models.IntegerField(blank=True, default=0, null=True)),
                ('Occupancy_In_Year', models.IntegerField(blank=True, default=0, null=True)),
                ('City', models.CharField(blank=True, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
    ]
