# Generated by Django 4.2.6 on 2023-12-05 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0003_alter_tradedata_tarrif'),
        ('general_data', '0014_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='Country',
            field=models.ForeignKey(default=505, on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta'),
            preserve_default=False,
        ),
    ]
