# Generated by Django 4.2.6 on 2023-12-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0016_rename_year_land_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism',
            name='Number_Of_Tourist',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
