# Generated by Django 4.2.6 on 2023-12-05 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0017_tourism_number_of_tourist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tourism',
            old_name='Tourism_code',
            new_name='Arrival_code',
        ),
    ]
