# Generated by Django 4.2.6 on 2023-12-06 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0003_alter_tradedata_tarrif'),
        ('general_data', '0018_rename_tourism_code_tourism_arrival_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourism',
            name='Nationality_Of_Tourism',
            field=models.ForeignKey(default=505, on_delete=django.db.models.deletion.CASCADE, related_name='Tourism_Nationality_Of_Tourism', to='trade_data.country_meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourism',
            name='Country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Tourism_Country', to='trade_data.country_meta'),
        ),
    ]
