# Generated by Django 4.2.6 on 2023-12-28 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0024_alter_land_code_meta_code'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='water',
            constraint=models.CheckConstraint(check=models.Q(('Unit', 'Cu Metre')), name='unit_must_be_cu_metre'),
        ),
    ]
