# Generated by Django 4.2.6 on 2023-12-31 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0025_water_unit_must_be_cu_metre'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='water',
            name='unit_must_be_cu_metre',
        ),
    ]
