# Generated by Django 4.2.6 on 2024-01-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0007_hs_code_meta_created_date_hs_code_meta_modified_date_and_more'),
        ('general_data', '0026_remove_water_unit_must_be_cu_metre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster_Data_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Disaster_Type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Energy_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Energy_Type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Health_disease_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Deasease_Type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Housing_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('House_Type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mine_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Mine_Type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Road_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Road_Type', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Public_Unitillity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Type_Of_Public_Utility', models.CharField(blank=True, max_length=100, null=True)),
                ('Number', models.IntegerField(blank=True, default=0, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Political_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Political_Party_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Number_Of_Member', models.IntegerField(blank=True, default=0, null=True)),
                ('Province', models.CharField(blank=True, max_length=30, null=True)),
                ('District', models.CharField(blank=True, max_length=30, null=True)),
                ('Municipality', models.CharField(blank=True, max_length=30, null=True)),
                ('Wards', models.CharField(blank=True, max_length=30, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Mining',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, choices=[('Mt', 'Mt')], max_length=10, null=True)),
                ('Current_Production', models.IntegerField(blank=True, default=0, null=True)),
                ('Potential_Stock', models.IntegerField(blank=True, default=0, null=True)),
                ('Mining_Company_Name', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Name_Of_Mine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.mine_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Housing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('City', models.CharField(blank=True, null=True)),
                ('Number', models.IntegerField(blank=True, default=0, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('House_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.housing_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Health_disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Unit', models.CharField(blank=True, choices=[('Person', 'Person')], max_length=20, null=True)),
                ('Number_Of_Case', models.IntegerField(blank=True, default=0, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Desease_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.health_disease_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Potential_Unit', models.CharField(blank=True, choices=[('Mt', 'Mt')], max_length=10, null=True)),
                ('Potential_Capacity_MW', models.IntegerField(blank=True, default=0, null=True)),
                ('Unit_Production', models.CharField(blank=True, choices=[('Megawat', 'Megawat')], max_length=20, null=True)),
                ('Current_Production_In_MW', models.IntegerField(blank=True, default=0, null=True)),
                ('Name_Of_The_Generating_Company', models.CharField(blank=True, max_length=100, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Power_Category_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.energy_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Disaster_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Human_Loss', models.IntegerField(blank=True, default=0, null=True)),
                ('Animal_Loss', models.IntegerField(blank=True, default=0, null=True)),
                ('Physical_Properties_Loss_In_USD', models.IntegerField(blank=True, default=0, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Disaster_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.disaster_data_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Budgetary_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Fiscal_Year', models.CharField(blank=True, max_length=10, null=True)),
                ('Amount_In_USD', models.IntegerField(blank=True, default=0, null=True)),
                ('Prefered_Denomination', models.CharField(blank=True, max_length=30, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
    ]
