# Generated by Django 5.0 on 2024-01-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0028_road'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Services_Type', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
