# Generated by Django 4.2.6 on 2024-01-10 08:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0028_road'),
    ]

    operations = [
        migrations.RenameField(
            model_name='health_disease',
            old_name='Desease_Code',
            new_name='Disease_Code',
        ),
        migrations.RenameField(
            model_name='health_disease_meta',
            old_name='Deasease_Type',
            new_name='Disease_Type',
        ),
        migrations.AddField(
            model_name='housing',
            name='Type_Of_House',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_of_house', to='general_data.housing_meta'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='housing',
            name='House_Code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_code', to='general_data.housing_meta'),
        ),
    ]
