# Generated by Django 5.0 on 2024-01-14 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0029_services_meta'),
        ('trade_data', '0011_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Direction', models.CharField(blank=True, choices=[('Import', 'Import'), ('Export', 'Export')], max_length=10, null=True)),
                ('Value', models.FloatField(blank=True, max_length=100, null=True)),
                ('Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.services_meta')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_country', to='trade_data.country_meta')),
                ('Origin_Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_origin_destination', to='trade_data.country_meta')),
            ],
        ),
    ]
