# Generated by Django 5.0 on 2024-01-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0030_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Code', models.CharField(max_length=100)),
                ('Name', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
