# Generated by Django 4.2.6 on 2024-01-11 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0031_rename_type_of_public_utility_public_unitillity_type_of_public_unitility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='public_unitillity',
            old_name='Type_Of_Public_Unitility',
            new_name='Type_Of_Public_Utility',
        ),
    ]
