# Generated by Django 5.0 on 2024-01-18 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0031_crime_meta'),
        ('trade_data', '0011_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crime',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.DateField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('District', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Offence_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.crime_meta')),
            ],
        ),
    ]
