# Generated by Django 5.0 on 2024-01-19 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0032_crime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crime',
            old_name='Offence_Code',
            new_name='Code',
        ),
    ]
