# Generated by Django 5.0 on 2024-01-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0033_rename_offence_code_crime_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crime',
            name='District',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
