# Generated by Django 5.0 on 2024-01-21 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0036_education_degree_meta_education_level_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Male', models.BigIntegerField(default=0)),
                ('Female', models.BigIntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Degree_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.education_degree_meta')),
                ('Level_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.education_level_meta')),
            ],
        ),
    ]
