# Generated by Django 5.0 on 2024-01-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0037_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('SOC_Code', models.CharField(max_length=100)),
                ('SOC_Group', models.TextField(blank=True, null=True)),
                ('SOC_Title', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
