# Generated by Django 5.0 on 2024-01-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0039_occupation'),
        ('trade_data', '0011_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate_Place_Meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Place_Code', models.CharField(max_length=20)),
                ('Place_Name', models.TextField()),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
            ],
        ),
        migrations.CreateModel(
            name='Climate_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField()),
                ('Max_Temperature', models.FloatField(max_length=100)),
                ('Min_Temperature', models.FloatField(max_length=100)),
                ('Climate', models.CharField(blank=True, choices=[('Rain', 'Rain'), ('Snow', 'Snow'), ('Storm', 'Storm')], max_length=20, null=True)),
                ('Amount', models.FloatField(max_length=100)),
                ('Climate_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaldata_climate_unit', to='trade_data.unit_meta')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Temperature_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaldata_temperature_unit', to='trade_data.unit_meta')),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.climate_place_meta')),
            ],
        ),
    ]
