# Generated by Django 4.2.6 on 2024-01-23 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0033_rename_length_unit_road_length_unit_options'),
        ('general_data', '0039_occupation'),
    ]

    operations = [
    ]
