# Generated by Django 4.2.6 on 2024-01-25 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0040_merge_20240123_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Road',
        ),
    ]
