# Generated by Django 5.0 on 2024-01-28 08:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0040_climate_place_meta'),
        ('trade_data', '0011_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='climate_place_meta',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Climate_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Date', models.DateField(blank=True, null=True)),
                ('Max_Temperature', models.FloatField(blank=True, max_length=100, null=True)),
                ('Min_Temperature', models.FloatField(blank=True, max_length=100, null=True)),
                ('Climate', models.CharField(blank=True, choices=[('Rain', 'Rain'), ('Snow', 'Snow'), ('Storm', 'Storm')], max_length=20, null=True)),
                ('Amount', models.FloatField(blank=True, max_length=100, null=True)),
                ('Climate_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaldata_climate_unit', to='trade_data.unit_meta')),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.climate_place_meta')),
                ('Temperature_Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generaldata_temperature_unit', to='trade_data.unit_meta')),
            ],
        ),
    ]
