# Generated by Django 4.2.6 on 2024-01-25 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0042_road'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Housing',
        ),
    ]
