# Generated by Django 4.2.6 on 2024-01-31 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0041_alter_climate_data_climate'),
        ('general_data', '0044_housing'),
    ]

    operations = [
    ]
