# Generated by Django 4.2.6 on 2024-02-01 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0045_merge_0041_alter_climate_data_climate_0044_housing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Disaster_Data',
        ),
    ]
