# Generated by Django 4.2.6 on 2024-02-01 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0011_alter_tradedata_tarrif'),
        ('general_data', '0046_delete_disaster_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster_Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Human_Loss', models.IntegerField(blank=True, default=0, null=True)),
                ('Animal_Loss', models.IntegerField(blank=True, default=0, null=True)),
                ('Physical_Properties_Loss_In_USD', models.IntegerField(blank=True, default=0, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Disaster_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.disaster_data_meta')),
            ],
        ),
    ]
