# Generated by Django 4.2.6 on 2024-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0047_disaster_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='health_disease',
            name='Country',
        ),
        migrations.RemoveField(
            model_name='health_disease',
            name='Disease_Code',
        ),
        migrations.RemoveField(
            model_name='health_disease',
            name='Number_Of_Case',
        ),
        migrations.RemoveField(
            model_name='health_disease',
            name='Unit',
        ),
        migrations.RemoveField(
            model_name='health_disease',
            name='Year',
        ),
        migrations.AlterField(
            model_name='health_disease',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
