# Generated by Django 4.2.6 on 2024-02-01 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_data', '0048_remove_health_disease_country_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Health_disease',
        ),
    ]
