# Generated by Django 4.2.6 on 2024-02-01 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0011_alter_tradedata_tarrif'),
        ('general_data', '0049_delete_health_disease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Health_disease',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.IntegerField()),
                ('Unit', models.CharField(blank=True, choices=[('Person', 'Person')], max_length=20, null=True)),
                ('Number_Of_Case', models.IntegerField(blank=True, default=0, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.country_meta')),
                ('Disease_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_data.health_disease_meta')),
            ],
        ),
    ]
