# Generated by Django 4.2.5 on 2023-10-08 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Country_Name', models.CharField(max_length=500)),
                ('Country_Code_2', models.CharField(blank=True, max_length=10, null=True)),
                ('Country_Code_3', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HS_Code_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('HS_Code', models.CharField(max_length=100)),
                ('Product_Information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradersName_ExporterImporter_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Unit_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Unit_Name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Trade_Type', models.CharField(blank=True, choices=[('import', 'Import'), ('export', 'Export')], max_length=100, null=True)),
                ('Calender', models.DateField(blank=True, null=True)),
                ('Fiscal_Year', models.CharField(blank=True, max_length=50, null=True)),
                ('Month_Duration', models.CharField(blank=True, max_length=50, null=True)),
                ('Product_Information', models.TextField()),
                ('Quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Currency_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=4, max_digits=200, null=True)),
                ('Tarrif', models.DecimalField(blank=True, decimal_places=4, max_digits=200, null=True)),
                ('DocumentsLegalProcedural', models.CharField(blank=True, max_length=300, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedata_country', to='import_export.country_meta')),
                ('HS_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_export.hs_code_meta')),
                ('Origin_Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedata_origin_destination', to='import_export.country_meta')),
                ('TradersName_ExporterImporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='import_export.tradersname_exporterimporter_meta')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import_export.unit_meta')),
            ],
        ),
    ]
