# Generated by Django 4.2.5 on 2023-10-05 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_export', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='Calender',
            field=models.DateField(blank=True, null=True),
        ),
    ]
