# Generated by Django 4.2.6 on 2023-10-30 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Country_Name', models.CharField(max_length=200)),
                ('Country_Code_2', models.CharField(blank=True, max_length=2, null=True)),
                ('Country_Code_3', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HS_Code_meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('HS_Code', models.CharField(max_length=100)),
                ('Product_Information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_meta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Unit_Code', models.CharField(max_length=50)),
                ('Unit_Name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Trade_Type', models.CharField(blank=True, choices=[('Import', 'Import'), ('Export', 'Export')], max_length=100, null=True)),
                ('Calender', models.DateField(blank=True, null=True)),
                ('Fiscal_Year', models.CharField(blank=True, max_length=10, null=True)),
                ('Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Currency_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True)),
                ('Tarrif', models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True)),
                ('TradersName_ExporterImporter', models.CharField(blank=True, max_length=100, null=True)),
                ('DocumentsLegalProcedural', models.CharField(blank=True, max_length=300, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedata_country', to='trade_data.country_meta')),
                ('HS_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.hs_code_meta')),
                ('Origin_Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedata_origin_destination', to='trade_data.country_meta')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trade_data.unit_meta')),
            ],
        ),
    ]
