# Generated by Django 4.2.6 on 2023-10-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_meta',
            name='Country_Code_2',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
