# Generated by Django 4.2.6 on 2023-12-19 07:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0004_country_meta_created_date_country_meta_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_meta',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='country_meta',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
