# Generated by Django 4.2.6 on 2023-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0005_alter_country_meta_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country_meta',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='country_meta',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
