# Generated by Django 5.0 on 2023-12-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0007_hs_code_meta_created_date_hs_code_meta_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='Tarrif',
            field=models.DecimalField(blank=True, decimal_places=3, default=0.0, max_digits=100, null=True),
        ),
    ]
