# Generated by Django 5.0 on 2023-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0008_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='Tarrif',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, max_digits=100, null=True),
        ),
    ]
