# Generated by Django 5.0 on 2023-12-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0009_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='Amount',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tradedata',
            name='Tarrif',
            field=models.FloatField(blank=True, default=0.0, max_length=100, null=True),
        ),
    ]
