# Generated by Django 5.0 on 2024-01-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade_data', '0010_alter_tradedata_amount_alter_tradedata_tarrif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradedata',
            name='Tarrif',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
