# Generated by Django 4.2.5 on 2023-10-09 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Country_Name', models.CharField(max_length=200)),
                ('Country_Code_2', models.CharField(blank=True, max_length=2, null=True)),
                ('Country_Code_3', models.CharField(blank=True, max_length=3, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HS_Code_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('HS_Code', models.CharField(max_length=100)),
                ('Product_Information', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TradersName_ExporterImporter_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Unit_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Unit_Code', models.CharField(blank=True, max_length=50, null=True)),
                ('Unit_Name', models.CharField(max_length=200)),
            ],
        ),
    ]
