# Generated by Django 4.2.5 on 2023-10-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HS_Code_meta',
        ),
    ]
