# Generated by Django 4.2.5 on 2023-10-09 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0002_delete_hs_code_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HS_Code_meta',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('HS_Code', models.CharField(max_length=100)),
                ('Product_Information', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
