# Generated by Django 4.2.5 on 2023-10-09 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0003_hs_code_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeData',
            fields=[
                ('id', models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('Trade_Type', models.CharField(blank=True, choices=[('Import', 'Import'), ('Export', 'Export')], max_length=100, null=True)),
                ('Calender', models.DateField(blank=True, null=True)),
                ('Fiscal_Year', models.CharField(blank=True, max_length=10, null=True)),
                ('Month_Duration', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('Currency_Type', models.CharField(blank=True, max_length=100, null=True)),
                ('Amount', models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True)),
                ('Tarrif', models.DecimalField(blank=True, decimal_places=3, max_digits=100, null=True)),
                ('TradersName_ExporterImporter', models.CharField(blank=True, max_length=100, null=True)),
                ('DocumentsLegalProcedural', models.CharField(blank=True, max_length=300, null=True)),
                ('Country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedata_country', to='import.country_meta')),
                ('HS_Code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import.hs_code_meta')),
                ('Origin_Destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradedata_origin_destination', to='import.country_meta')),
                ('Unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='import.unit_meta')),
            ],
        ),
    ]
