# Generated by Django 4.2.5 on 2023-10-09 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('import', '0004_tradedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tradedata',
            old_name='Month_Duration',
            new_name='Duration',
        ),
    ]
